package io.github.klaw.common.config.schema

import io.github.klaw.common.config.ConfigPropertyDescriptor
import io.github.klaw.common.config.ConfigValueType

// AUTO-GENERATED — do not edit manually. Run generateSchemas task to regenerate.

object GeneratedConfigDescriptors {
    val ENGINE: List<ConfigPropertyDescriptor> =
        listOf(
            ConfigPropertyDescriptor(
                "providers",
                ConfigValueType.MAP_SECTION,
                "LLM provider definitions keyed by provider name",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "providers.*.type",
                ConfigValueType.STRING,
                "Provider API type",
                null,
                listOf("openai"),
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "providers.*.endpoint",
                ConfigValueType.STRING,
                "API endpoint URL for this provider",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "providers.*.apiKey",
                ConfigValueType.STRING,
                "API key for authentication",
                null,
                null,
                true,
                false,
            ),
            ConfigPropertyDescriptor(
                "models",
                ConfigValueType.MAP_SECTION,
                "Model override settings keyed by provider/modelId",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "models.*.maxTokens",
                ConfigValueType.INT,
                "Maximum output tokens for completions",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "models.*.contextBudget",
                ConfigValueType.INT,
                "Maximum input context budget in tokens",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "models.*.temperature",
                ConfigValueType.DOUBLE,
                "Sampling temperature for generation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "routing.default",
                ConfigValueType.STRING,
                "Default model reference as provider/modelId",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "routing.fallback",
                ConfigValueType.LIST_STRING,
                "Fallback model references tried in order if default fails",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "routing.tasks.summarization",
                ConfigValueType.STRING,
                "Model reference for summarization tasks",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "routing.tasks.subagent",
                ConfigValueType.STRING,
                "Model reference for subagent tasks",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "memory.embedding.type",
                ConfigValueType.STRING,
                "Embedding backend type",
                null,
                listOf("onnx", "ollama"),
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "memory.embedding.model",
                ConfigValueType.STRING,
                "Embedding model name or path",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "memory.chunking.size",
                ConfigValueType.INT,
                "Maximum chunk size in characters",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "memory.chunking.overlap",
                ConfigValueType.INT,
                "Overlap between consecutive chunks in characters",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "memory.search.topK",
                ConfigValueType.INT,
                "Number of top results to return from hybrid search",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "context.defaultBudgetTokens",
                ConfigValueType.INT,
                "Default token budget for historical messages in the context window",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "context.subagentHistory",
                ConfigValueType.INT,
                "Maximum number of history runs to include for subagents",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "processing.debounceMs",
                ConfigValueType.LONG,
                "Delay in milliseconds before processing buffered messages",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "processing.maxConcurrentLlm",
                ConfigValueType.INT,
                "Maximum number of concurrent LLM API requests",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "processing.maxToolCallRounds",
                ConfigValueType.INT,
                "Maximum number of tool-call rounds per conversation turn",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "processing.maxToolOutputChars",
                ConfigValueType.INT,
                "Maximum characters in tool output before truncation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "processing.maxDebounceEntries",
                ConfigValueType.INT,
                "Maximum messages in the debounce buffer before force-flush",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "llm.maxRetries",
                ConfigValueType.INT,
                "Maximum number of retry attempts on transient API errors",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "llm.requestTimeoutMs",
                ConfigValueType.LONG,
                "HTTP request timeout in milliseconds",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "llm.initialBackoffMs",
                ConfigValueType.LONG,
                "Initial backoff delay in milliseconds before first retry",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "llm.backoffMultiplier",
                ConfigValueType.DOUBLE,
                "Multiplier applied to backoff delay after each retry",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "logging.subagentConversations",
                ConfigValueType.BOOLEAN,
                "Log subagent conversation JSONL files for debugging",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.dockerImage",
                ConfigValueType.STRING,
                "Docker image used for code execution sandbox",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.timeout",
                ConfigValueType.INT,
                "Maximum execution timeout in seconds",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.allowNetwork",
                ConfigValueType.BOOLEAN,
                "Allow network access inside the sandbox container",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.maxMemory",
                ConfigValueType.STRING,
                "Maximum memory limit for the sandbox container",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.maxCpus",
                ConfigValueType.STRING,
                "Maximum CPU cores for the sandbox container",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.readOnlyRootfs",
                ConfigValueType.BOOLEAN,
                "Mount the container root filesystem as read-only",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.keepAlive",
                ConfigValueType.BOOLEAN,
                "Keep sandbox container alive between executions (reuses container for faster execution and state persistence)",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.keepAliveIdleTimeoutMin",
                ConfigValueType.INT,
                "Idle timeout in minutes before stopping a kept-alive container",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.keepAliveMaxExecutions",
                ConfigValueType.INT,
                "Maximum executions before recycling a kept-alive container",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.volumeMounts",
                ConfigValueType.LIST_STRING,
                "Additional Docker volume mounts for the sandbox",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "files.maxFileSizeBytes",
                ConfigValueType.LONG,
                "Maximum file size in bytes that file tools can read",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "commands[].name",
                ConfigValueType.STRING,
                "Slash command name without the leading /",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "commands[].description",
                ConfigValueType.STRING,
                "Human-readable description shown in command help",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "compatibility.openclaw.enabled",
                ConfigValueType.BOOLEAN,
                "Enable OpenClaw compatibility mode",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "compatibility.openclaw.sync.memoryMd",
                ConfigValueType.BOOLEAN,
                "Sync MEMORY.md file with OpenClaw",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "compatibility.openclaw.sync.dailyLogs",
                ConfigValueType.BOOLEAN,
                "Sync daily log files with OpenClaw",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "compatibility.openclaw.sync.userMd",
                ConfigValueType.BOOLEAN,
                "Sync USER.md file with OpenClaw",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "autoRag.enabled",
                ConfigValueType.BOOLEAN,
                "Enable automatic RAG retrieval for conversation context",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "autoRag.topK",
                ConfigValueType.INT,
                "Number of top relevant messages to retrieve",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "autoRag.maxTokens",
                ConfigValueType.INT,
                "Maximum tokens of auto-RAG context to inject",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "autoRag.relevanceThreshold",
                ConfigValueType.DOUBLE,
                "Minimum relevance score threshold for including results",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "autoRag.minMessageTokens",
                ConfigValueType.INT,
                "Minimum token count in a message to trigger auto-RAG",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "docs.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the documentation tool for workspace docs",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "skills.maxInlineSkills",
                ConfigValueType.INT,
                "Maximum number of skills included inline in the system prompt",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.enabled",
                ConfigValueType.BOOLEAN,
                "Enable host command execution outside Docker sandbox",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.allowList",
                ConfigValueType.LIST_STRING,
                "Commands allowed to run without user confirmation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.notifyList",
                ConfigValueType.LIST_STRING,
                "Commands that trigger a notification to the user",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.preValidation.enabled",
                ConfigValueType.BOOLEAN,
                "Enable LLM-based pre-validation of host commands",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.preValidation.model",
                ConfigValueType.STRING,
                "Model reference used for pre-validation checks",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.preValidation.riskThreshold",
                ConfigValueType.INT,
                "Risk score threshold above which commands are blocked",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.preValidation.timeoutMs",
                ConfigValueType.LONG,
                "Timeout in milliseconds for the pre-validation LLM call",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.askTimeoutMin",
                ConfigValueType.INT,
                "Timeout in minutes for user confirmation prompts (0 = infinite, no timeout)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "heartbeat.interval",
                ConfigValueType.STRING,
                "Heartbeat interval as a cron expression or 'off' to disable",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "heartbeat.model",
                ConfigValueType.STRING,
                "Model reference used for heartbeat generation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "heartbeat.injectInto",
                ConfigValueType.STRING,
                "Session name to inject heartbeat output into",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "heartbeat.channel",
                ConfigValueType.STRING,
                "Channel to deliver heartbeat messages to",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "summarization.enabled",
                ConfigValueType.BOOLEAN,
                "Enable background summarization of old messages",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "summarization.tokenThreshold",
                ConfigValueType.INT,
                "Token threshold: summarize when this many tokens fall out of the sliding window",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "summarization.summaryBudgetFraction",
                ConfigValueType.DOUBLE,
                "Fraction of context budget allocated to summaries (0.0 to 1.0, exclusive)",
                null,
                null,
                false,
                false,
            ),
        )

    val GATEWAY: List<ConfigPropertyDescriptor> =
        listOf(
            ConfigPropertyDescriptor(
                "channels.telegram.token",
                ConfigValueType.STRING,
                "Telegram Bot API token",
                null,
                null,
                true,
                true,
            ),
            ConfigPropertyDescriptor(
                "channels.telegram.allowedChats[].chatId",
                ConfigValueType.STRING,
                "Platform-specific chat identifier",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "channels.telegram.allowedChats[].allowedUserIds",
                ConfigValueType.LIST_STRING,
                "List of user IDs allowed to interact in this chat",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.discord.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the Discord bot channel",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.discord.token",
                ConfigValueType.STRING,
                "Discord bot token",
                null,
                null,
                true,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.console.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the console debug channel",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.console.port",
                ConfigValueType.INT,
                "TCP port for the console debug channel",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "commands[].name",
                ConfigValueType.STRING,
                "Slash command name without the leading /",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "commands[].description",
                ConfigValueType.STRING,
                "Human-readable description shown in command help",
                null,
                null,
                false,
                true,
            ),
        )
}
