package io.github.klaw.common.config.schema

import io.github.klaw.common.config.ConfigPropertyDescriptor
import io.github.klaw.common.config.ConfigValueType

// AUTO-GENERATED — do not edit manually. Run generateSchemas task to regenerate.

object GeneratedConfigDescriptors {
    val ENGINE: List<ConfigPropertyDescriptor> =
        listOf(
            ConfigPropertyDescriptor(
                "workspace",
                ConfigValueType.STRING,
                "Workspace directory path (overrides KLAW_WORKSPACE env var)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "providers",
                ConfigValueType.MAP_SECTION,
                "LLM provider definitions keyed by provider name",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "providers.*.type",
                ConfigValueType.STRING,
                "Provider API type (resolved from built-in registry if omitted)",
                null,
                listOf("openai-compatible", "anthropic"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "providers.*.endpoint",
                ConfigValueType.STRING,
                "API endpoint URL (resolved from built-in registry if omitted)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "providers.*.apiKey",
                ConfigValueType.STRING,
                "API key for authentication",
                null,
                null,
                true,
                false,
            ),
            ConfigPropertyDescriptor(
                "models",
                ConfigValueType.MAP_SECTION,
                "Model override settings keyed by provider/modelId",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "models.*.temperature",
                ConfigValueType.DOUBLE,
                "Sampling temperature for generation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "routing.default",
                ConfigValueType.STRING,
                "Default model reference as provider/modelId",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "routing.fallback",
                ConfigValueType.LIST_STRING,
                "Fallback model references tried in order if default fails",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "routing.tasks.summarization",
                ConfigValueType.STRING,
                "Model reference for summarization tasks",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "routing.tasks.subagent",
                ConfigValueType.STRING,
                "Model reference for subagent tasks",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "routing.tasks.consolidation",
                ConfigValueType.STRING,
                "Model reference for consolidation tasks",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.embedding.type",
                ConfigValueType.STRING,
                "Embedding backend type",
                null,
                listOf("onnx", "ollama"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.embedding.model",
                ConfigValueType.STRING,
                "Embedding model name (ONNX directory name or Ollama model identifier)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.embedding.ollamaFallbackModel",
                ConfigValueType.STRING,
                "Ollama model name used when falling back from ONNX (default: multilingual-e5-small)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.chunking.size",
                ConfigValueType.INT,
                "Maximum chunk size in approximate tokens",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.chunking.overlap",
                ConfigValueType.INT,
                "Overlap between consecutive chunks in approximate tokens",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.search.topK",
                ConfigValueType.INT,
                "Number of top results to return from hybrid search",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "memory.search.mmr.enabled",
                ConfigValueType.BOOLEAN,
                "Enable MMR diversity reranking for memory search results",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.search.mmr.lambda",
                ConfigValueType.DOUBLE,
                "Relevance vs diversity tradeoff (0.0=max diversity, 1.0=pure relevance)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.search.temporalDecay.enabled",
                ConfigValueType.BOOLEAN,
                "Enable temporal decay — recent memories score higher than old ones",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.search.temporalDecay.halfLifeDays",
                ConfigValueType.INT,
                "Half-life in days — after this many days, score is halved",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.injectMemoryMap",
                ConfigValueType.BOOLEAN,
                "Inject a Memory Map of database categories into the system prompt",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.mapMaxCategories",
                ConfigValueType.INT,
                "Maximum number of categories displayed in the memory map",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.autoRag.enabled",
                ConfigValueType.BOOLEAN,
                "Enable automatic RAG retrieval for conversation context",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.autoRag.topK",
                ConfigValueType.INT,
                "Number of top relevant messages to retrieve",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.autoRag.maxTokens",
                ConfigValueType.INT,
                "Maximum tokens of auto-RAG context to inject",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.autoRag.relevanceThreshold",
                ConfigValueType.DOUBLE,
                "Minimum relevance score threshold for including results",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.autoRag.minMessageTokens",
                ConfigValueType.INT,
                "Minimum token count in a message to trigger auto-RAG",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.compaction.enabled",
                ConfigValueType.BOOLEAN,
                "Enable background summarization of old messages",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.compaction.compactionThresholdFraction",
                ConfigValueType.DOUBLE,
                "Fraction of context budget that defines the compaction zone (0.0 to 1.0, exclusive)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.compaction.summaryBudgetFraction",
                ConfigValueType.DOUBLE,
                "Fraction of context budget allocated to summaries (0.0 to 1.0, exclusive)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.consolidation.enabled",
                ConfigValueType.BOOLEAN,
                "Enable daily memory consolidation",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.consolidation.cron",
                ConfigValueType.STRING,
                "Cron expression for consolidation schedule",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.consolidation.model",
                ConfigValueType.STRING,
                "Model reference for consolidation LLM call (empty = use summarization model)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.consolidation.excludeChannels",
                ConfigValueType.LIST_STRING,
                "Channels to exclude from consolidation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.consolidation.category",
                ConfigValueType.STRING,
                "Memory category hint for consolidation summaries",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "memory.consolidation.minMessages",
                ConfigValueType.INT,
                "Minimum number of messages required to trigger consolidation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "context.tokenBudget",
                ConfigValueType.INT,
                "Token budget for context window. Priority: config > model registry > 100000.",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "context.subagentHistory",
                ConfigValueType.INT,
                "Maximum number of history runs to include for subagents",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "processing.debounceMs",
                ConfigValueType.LONG,
                "Delay in milliseconds before processing buffered messages",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "processing.maxConcurrentLlm",
                ConfigValueType.INT,
                "Maximum number of concurrent LLM API requests",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "processing.maxToolCallRounds",
                ConfigValueType.INT,
                "Maximum number of tool-call rounds per conversation turn",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "processing.maxToolOutputChars",
                ConfigValueType.INT,
                "Maximum characters in tool output before truncation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "processing.maxDebounceEntries",
                ConfigValueType.INT,
                "Maximum messages in the debounce buffer before force-flush",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "processing.subagentTimeoutMs",
                ConfigValueType.LONG,
                "Subagent execution timeout in milliseconds (default 5 minutes)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "processing.streaming.enabled",
                ConfigValueType.BOOLEAN,
                "Enable streaming for interactive responses",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "processing.streaming.throttleMs",
                ConfigValueType.LONG,
                "Minimum interval between stream deltas sent to gateway (ms)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "skills.maxInlineSkills",
                ConfigValueType.INT,
                "Maximum number of skills included inline in the system prompt",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "commands[].name",
                ConfigValueType.STRING,
                "Slash command name without the leading /",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "commands[].description",
                ConfigValueType.STRING,
                "Human-readable description shown in command help",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "heartbeat.interval",
                ConfigValueType.STRING,
                "Heartbeat interval as ISO-8601 duration (e.g. PT1H, PT30M) or 'off' to disable",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "heartbeat.model",
                ConfigValueType.STRING,
                "Model reference used for heartbeat generation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "heartbeat.injectInto",
                ConfigValueType.STRING,
                "Session name to inject heartbeat output into",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "heartbeat.channel",
                ConfigValueType.STRING,
                "Channel to deliver heartbeat messages to",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "files.maxFileSizeBytes",
                ConfigValueType.LONG,
                "Maximum file size in bytes that file tools can read",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.dockerImage",
                ConfigValueType.STRING,
                "Docker image used for code execution sandbox",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.timeout",
                ConfigValueType.INT,
                "Maximum execution timeout in seconds",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.allowNetwork",
                ConfigValueType.BOOLEAN,
                "Allow network access inside the sandbox container",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.maxMemory",
                ConfigValueType.STRING,
                "Maximum memory limit for the sandbox container",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.maxCpus",
                ConfigValueType.STRING,
                "Maximum CPU cores for the sandbox container",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.readOnlyRootfs",
                ConfigValueType.BOOLEAN,
                "Mount the container root filesystem as read-only",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.keepAlive",
                ConfigValueType.BOOLEAN,
                "Keep sandbox container alive between executions (reuses container for faster execution and state persistence)",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.keepAliveIdleTimeoutMin",
                ConfigValueType.INT,
                "Idle timeout in minutes before stopping a kept-alive container",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.keepAliveMaxExecutions",
                ConfigValueType.INT,
                "Maximum executions before recycling a kept-alive container",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.volumeMounts",
                ConfigValueType.LIST_STRING,
                "Additional Docker volume mounts for the sandbox",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "codeExecution.runAsUser",
                ConfigValueType.STRING,
                "User:group ID for sandbox container process (default: 1000:1000)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.enabled",
                ConfigValueType.BOOLEAN,
                "Enable host command execution outside Docker sandbox",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.allowList",
                ConfigValueType.LIST_STRING,
                "Commands allowed to run without user confirmation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.notifyList",
                ConfigValueType.LIST_STRING,
                "Commands that trigger a notification to the user",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.preValidation.enabled",
                ConfigValueType.BOOLEAN,
                "Enable LLM-based pre-validation of host commands",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.preValidation.model",
                ConfigValueType.STRING,
                "Model reference used for pre-validation checks",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.preValidation.riskThreshold",
                ConfigValueType.INT,
                "Risk score threshold above which commands are blocked",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.preValidation.timeoutMs",
                ConfigValueType.LONG,
                "Timeout in milliseconds for the pre-validation LLM call",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "hostExecution.askTimeoutMin",
                ConfigValueType.INT,
                "Timeout in minutes for user confirmation prompts (0 = infinite, no timeout)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.fetch.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the web_fetch tool for fetching web page content",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.fetch.requestTimeoutMs",
                ConfigValueType.LONG,
                "HTTP request timeout in milliseconds",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.fetch.maxResponseSizeBytes",
                ConfigValueType.LONG,
                "Maximum response body size in bytes (default 1MB)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.fetch.userAgent",
                ConfigValueType.STRING,
                "User-Agent header sent with requests",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.search.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the web_search tool for searching the internet",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.search.provider",
                ConfigValueType.STRING,
                "Search provider type",
                null,
                listOf("brave", "tavily"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.search.apiKey",
                ConfigValueType.STRING,
                "API key for the search provider",
                null,
                null,
                true,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.search.maxResults",
                ConfigValueType.INT,
                "Maximum number of search results to return",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.search.requestTimeoutMs",
                ConfigValueType.LONG,
                "HTTP request timeout in milliseconds",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.search.braveEndpoint",
                ConfigValueType.STRING,
                "Brave Search API endpoint URL (override for testing)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "web.search.tavilyEndpoint",
                ConfigValueType.STRING,
                "Tavily Search API endpoint URL (override for testing)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "documents.maxPdfSizeBytes",
                ConfigValueType.LONG,
                "Maximum PDF file size in bytes for pdf_read (default 50MB)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "documents.maxPages",
                ConfigValueType.INT,
                "Maximum number of pages to extract in pdf_read (0 = unlimited)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "documents.maxOutputChars",
                ConfigValueType.INT,
                "Maximum output text length in characters before truncation",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "documents.pdfFontSize",
                ConfigValueType.DOUBLE,
                "Default font size for md_to_pdf output",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "vision.enabled",
                ConfigValueType.BOOLEAN,
                "Enable vision/image analysis capabilities",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "vision.model",
                ConfigValueType.STRING,
                "Model reference for vision analysis (e.g. 'glm/glm-4.6v')",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "vision.maxTokens",
                ConfigValueType.INT,
                "Maximum output tokens for vision model responses (null = use model registry default)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "vision.maxImageSizeBytes",
                ConfigValueType.LONG,
                "Maximum image file size in bytes (default 10MB)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "vision.maxImagesPerMessage",
                ConfigValueType.INT,
                "Maximum images per message for inline vision",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "vision.supportedFormats",
                ConfigValueType.LIST_STRING,
                "Supported image MIME types",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "vision.attachmentsDirectory",
                ConfigValueType.STRING,
                "Directory where gateway stores image attachments (must match gateway attachments.directory)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "httpRetry.maxRetries",
                ConfigValueType.INT,
                "Maximum number of retry attempts on transient API errors",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "httpRetry.requestTimeoutMs",
                ConfigValueType.LONG,
                "HTTP request timeout in milliseconds",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "httpRetry.initialBackoffMs",
                ConfigValueType.LONG,
                "Initial backoff delay in milliseconds before first retry",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "httpRetry.backoffMultiplier",
                ConfigValueType.DOUBLE,
                "Multiplier applied to backoff delay after each retry",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "database.busyTimeoutMs",
                ConfigValueType.INT,
                "SQLite busy timeout in milliseconds",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "database.integrityCheckOnStartup",
                ConfigValueType.BOOLEAN,
                "Run PRAGMA integrity_check on startup",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "database.backupEnabled",
                ConfigValueType.BOOLEAN,
                "Enable automatic database backups",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "database.backupInterval",
                ConfigValueType.STRING,
                "Backup interval as ISO-8601 duration",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "database.backupMaxCount",
                ConfigValueType.INT,
                "Maximum number of backup files to keep",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "logging.subagentConversations",
                ConfigValueType.BOOLEAN,
                "Log subagent conversation JSONL files for debugging",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "docs.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the documentation tool for workspace docs",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
        )

    val GATEWAY: List<ConfigPropertyDescriptor> =
        listOf(
            ConfigPropertyDescriptor(
                "channels.telegram.token",
                ConfigValueType.STRING,
                "Telegram Bot API token",
                null,
                null,
                true,
                true,
            ),
            ConfigPropertyDescriptor(
                "channels.telegram.allowedChats[].chatId",
                ConfigValueType.STRING,
                "Platform-specific chat identifier",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "channels.telegram.allowedChats[].allowedUserIds",
                ConfigValueType.LIST_STRING,
                "List of user IDs allowed to interact in this chat",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.telegram.apiBaseUrl",
                ConfigValueType.STRING,
                "Custom API base URL (testing only)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.discord.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the Discord bot channel",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.discord.token",
                ConfigValueType.STRING,
                "Discord bot token",
                null,
                null,
                true,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.discord.allowedGuilds[].guildId",
                ConfigValueType.STRING,
                "Discord guild (server) ID",
                null,
                null,
                false,
                true,
            ),
            ConfigPropertyDescriptor(
                "channels.discord.allowedGuilds[].allowedChannelIds",
                ConfigValueType.LIST_STRING,
                "Allowed channel IDs within guild (empty = all channels)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.discord.allowedGuilds[].allowedUserIds",
                ConfigValueType.LIST_STRING,
                "Allowed user IDs (empty = deny all)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.discord.apiBaseUrl",
                ConfigValueType.STRING,
                "Custom API base URL (testing only)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.localWs.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the local WebSocket channel",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "channels.localWs.port",
                ConfigValueType.INT,
                "TCP port for the local WebSocket channel",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "delivery.maxReconnectAttempts",
                ConfigValueType.INT,
                "Max consecutive reconnect failures before giving up (0 = unlimited)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "delivery.drainBudgetSeconds",
                ConfigValueType.INT,
                "Max seconds for draining inbound buffer on reconnect (0 = unlimited)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "delivery.channelDrainBudgetSeconds",
                ConfigValueType.INT,
                "Max seconds for draining per-channel buffer (0 = unlimited)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "attachments.directory",
                ConfigValueType.STRING,
                "Directory for storing received image attachments (empty = disabled)",
                null,
                null,
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "webui.enabled",
                ConfigValueType.BOOLEAN,
                "Enable the Web UI (REST API + SPA)",
                null,
                listOf("true", "false"),
                false,
                false,
            ),
            ConfigPropertyDescriptor(
                "webui.apiToken",
                ConfigValueType.STRING,
                "Bearer token for API authentication (supports \${ENV_VAR} substitution, empty = no auth)",
                null,
                null,
                false,
                false,
            ),
        )
}
